language: python
sudo: false

python:
  - '3.7-dev'
  - '3.6'
  - '3.5'
  - '3.4'
  - '2.7'

install: pip install invoke pipenv

script:
  - invoke setup --skip-lock --version ${TRAVIS_PYTHON_VERSION:0:3}
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7-dev' ]]; then invoke fmt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7-dev' ]]; then invoke lint; fi
  - invoke unit-test
